// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Payload<Data = any> {
    transactionId: string;
    actionIndex:   number;
    account:       string;
    name:          string;
    authorization: Authorization[];
    data:          Data;
}

export interface Authorization {
    actor:      string;
    permission: string;
}
